using BTCPayServer.Plugins.ArkPayServer.Data;
using BTCPayServer.Plugins.ArkPayServer.Services;
using NArk.Abstractions.Contracts;
using NArk.Abstractions.VTXOs;
using NArk.Abstractions.Wallets;
using NBitcoin;
namespace BTCPayServer.Plugins.ArkPayServer.Models;

public class StoreOverviewViewModel
{
    public string? StoreId { get; set; }
    public bool IsLightningEnabled { get; set; }
    public bool IsDestinationSweepEnabled { get; set; }
    public ArkBalancesViewModel? Balances { get; set; }
    public string? WalletId { get; set; }
    public string? Destination { get; set; }
    public bool SignerAvailable { get; set; }
    public string? Wallet { get; set; }
    public string? DefaultAddress { get; set; }
    public bool AllowSubDustAmounts { get; set; }
    public bool BoardingEnabled { get; set; }
    public long MinBoardingAmountSats { get; set; }

    /// <summary>
    /// The type of wallet (SingleKey/legacy or HD/mnemonic).
    /// </summary>
    public WalletType WalletType { get; set; }

    /// <summary>
    /// Whether the current user can manage private keys (spend funds, view keys).
    /// True if the wallet was generated by this store OR user is a server admin.
    /// </summary>
    public bool CanManagePrivateKeys { get; set; }

    /// <summary>
    /// True when the wallet's sweep destination was disabled because a signer rotation
    /// made it stale. The SDK sets <c>destination:pendingConfirmation</c> in wallet
    /// metadata and pauses sweeping until the merchant re-confirms a current-signer address.
    /// </summary>
    public bool DestinationPendingConfirmation { get; set; }

    /// <summary>Status of the most recent background wallet-recovery run (import or Rescan), if any.</summary>
    public RecoveryStatus? RecoveryStatus { get; set; }

    // Service connection status
    public string? ArkOperatorUrl { get; set; }
    public bool ArkOperatorConnected { get; set; }
    public string? ArkOperatorError { get; set; }
    
    /// <summary>The relay the Arkade swap solver is reached on, when one is configured.</summary>
    public string? SolverRelayUrl { get; set; }

    /// <summary>The solver's x-only public key, hex — its identity on the relay.</summary>
    public string? SolverPubkey { get; set; }

    /// <summary>Whether both halves needed to reach a solver are configured.</summary>
    /// <remarks>
    /// Configured, not connected — and the distinction is worth keeping in the name. Both sides of
    /// this transport dial out and neither listens, so there is nothing to ping: the first evidence a
    /// solver is actually there is a quote coming back. Reporting "connected" from a relay URL being
    /// present would be reporting something nobody checked.
    /// </remarks>
    public bool SolverConfigured { get; set; }

    // VTXOs for the overview (recent unspent)
    public IReadOnlyCollection<ArkVtxo> RecentVtxos { get; set; } = [];
    public HashSet<OutPoint> SpendableOutpoints { get; set; } = [];
    public Dictionary<string, ArkContractEntity> VtxoContracts { get; set; } = new();
    public int TotalVtxoCount { get; set; }

    // Recent intents
    public IReadOnlyCollection<NArk.Abstractions.Intents.ArkIntent> RecentIntents { get; set; } = [];
    public int TotalIntentCount { get; set; }
}